version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - server/.env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
